### PR TITLE
fixed responsiveness majorly, kept most of the maintainer designs

### PR DESCRIPTION
**Pull request by JaeKralj**
I fixed a bit of reposiveness on the frontend, whilst keeping the designs of maintainers intact. Having worked on the frontend before, I saw some bug as regards the styling with color and accessbility and all now fixed.... I also fixed the overlay breakage in the predict.html

### CODE REVIEW

**Review by osinkolu — APPROVED** [review]
Thanks for fixing this, @JaeKralj, I have manually reviewed your code, as there is no CI-CD yet. I'll now merge your fix with production.

**Comment by osinkolu** [comment]
@JaeKralj your updates are now live in production.

**Comment by osinkolu** [comment]
@JaeKralj I noticed some challenges with the merge request. We'll probably need staging, but we can break and reverse things while this is still a prototype project. can you push a fix for this? Or should I roll back the changes?

image

**Comment by JaeKralj** [comment]
how can i fix this please?

**Comment by osinkolu** [comment]
Hi @JaeKralj, I'm not too sure. I think it has something to do with the front end, or perhaps two files (logos) have the same name. Can you check your local development to see how this reflects?

**Comment by JaeKralj** [comment]
Okay I'd check thanks

**Pull request merged**
